spring:
  application:
    name: ecommerce-api

  datasource:
    url: jdbc:postgresql://dpg-d6k55knafjfc73ffefsg-a/murgan_pl46?user=murgan_pl46_user&password=FdMKLDZrMoQAAOeu08XmZxQOYJU1A9tv
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          generate_statistics: false

server:
  port: ${PORT:8080}

security:
  jwt:
    secret: f9K#2vLxQ8!aZr7P@6YdT3m$W1uC%J4hG0sB^nR5qE&Xk9*Vt8zF2pL7wH!cM6oD#S1yU@bN3iK%Qx4A$Zr5Tg7Jd8Wm9P2E^vC0YhF!kL6sB3Xn&uR1qH8oD4zVtM5G2pS7c9a
    access-token-ttl-seconds: ${SECURITY_JWT_ACCESS_TOKEN_TTL_SECONDS:900}

app:
  cors:
    allowed-origins: "https://murgan-ui.vercel.app/,http://localhost:3000"
  bootstrap-admin:
    enabled: ${APP_BOOTSTRAP_ADMIN_ENABLED:true}
    email: ${APP_BOOTSTRAP_ADMIN_EMAIL:admin123@local}
    username: ${APP_BOOTSTRAP_ADMIN_USERNAME:admin123}
    password: ${APP_BOOTSTRAP_ADMIN_PASSWORD:123@admin}